[package]
name = "msrlint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.4", features = ["derive"] }
swc = "0.106.2"
swc_common = { version = "0.16.0", features = ["tty-emitter"] }
swc_ecmascript = { version = "0.103.2", features = ["parser", "utils", "transforms", "visit"] }
swc_estree_ast = "0.6.0"
walkdir = "2.3.2"